//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workingtime
    {
        public int WorkingTimeID { get; set; }
        public int CompanyID { get; set; }
        public bool MoDayOff { get; set; }
        public Nullable<System.TimeSpan> MoStartFrom { get; set; }
        public Nullable<System.TimeSpan> MoWorkTo { get; set; }
        public bool TuDayOff { get; set; }
        public Nullable<System.TimeSpan> TuStartFrom { get; set; }
        public Nullable<System.TimeSpan> TuWorkTo { get; set; }
        public bool WeDayOff { get; set; }
        public Nullable<System.TimeSpan> WeStartFrom { get; set; }
        public Nullable<System.TimeSpan> WeWorkTo { get; set; }
        public bool ThDayOff { get; set; }
        public Nullable<System.TimeSpan> ThStartFrom { get; set; }
        public Nullable<System.TimeSpan> ThWorkTo { get; set; }
        public bool FrDayOff { get; set; }
        public Nullable<System.TimeSpan> FrStartFrom { get; set; }
        public Nullable<System.TimeSpan> FrWorkTo { get; set; }
        public bool SaDayOff { get; set; }
        public Nullable<System.TimeSpan> SaStartFrom { get; set; }
        public Nullable<System.TimeSpan> SaWorkTo { get; set; }
        public bool SuDayOff { get; set; }
        public Nullable<System.TimeSpan> SuStartFrom { get; set; }
        public Nullable<System.TimeSpan> SuWorkTo { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
